/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
export const command = "line-items <command>";
export const description = `[Link to documentation](https://help.getharvest.com/api-v2/invoices-api/invoices/invoices/#the-invoice-line-item-object)`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .commandDir("line-items")
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
