/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "messages <command>";
export const description = `Information pertaining to retrieving, creating, and deleting estimate messages, as well as accepting, declining, and re-opening estimates. Admin permissions required.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("messages").version(false);
export const handler = () => {};
