/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
import { commands } from "./messages/index";
export const command = "messages <command>";
export const description = `Information pertaining to retrieving, creating, and deleting estimate messages, as well as accepting, declining, and re-opening estimates. Admin permissions required.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .command(commands)
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
