/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./create";
import * as c1 from "./delete-external-reference";
import * as c2 from "./delete";
import * as c3 from "./get";
import * as c4 from "./list";
import * as c5 from "./restart";
import * as c6 from "./stop";
import * as c7 from "./update";
export const commands = [c0, c1, c2, c3, c4, c5, c6, c7];
