/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "GET",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "time_entries"],
    query: [
      {
        key: "user_id",
        value: "",
        description:
          "Only return time entries belonging to the user with the given ID.",
        disabled: true,
      },
      {
        key: "client_id",
        value: "",
        description:
          "Only return time entries belonging to the client with the given ID.",
        disabled: true,
      },
      {
        key: "task_id",
        value: "",
        description:
          "Only return time entries belonging to the task with the given ID.",
        disabled: true,
      },
      {
        key: "external_reference_id",
        value: "",
        description:
          "Only return time entries with the given external_reference ID.",
        disabled: true,
      },
      {
        key: "is_billed",
        value: "",
        description:
          "Pass true to only return time entries that have been invoiced and false to return time entries that have not been invoiced.",
        disabled: true,
      },
      {
        key: "is_running",
        value: "",
        description:
          "Pass true to only return running time entries and false to return non-running time entries.",
        disabled: true,
      },
      {
        key: "updated_since",
        value: "",
        description:
          "Only return time entries that have been updated since the given date and time.",
        disabled: true,
      },
      {
        key: "from",
        value: "",
        description:
          "Only return time entries with a spent_date on or after the given date.",
        disabled: true,
      },
      {
        key: "to",
        value: "",
        description:
          "Only return time entries with a spent_date on or before the given date.",
        disabled: true,
      },
      {
        key: "page",
        value: "",
        description:
          "The page number to use in pagination. Use `all` to retrieve all pages.",
        disabled: true,
      },
      {
        key: "per_page",
        value: "",
        description:
          "The number of records to return per page. Can range between 1 and 2000.  ",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "list",
    describe: "Returns a list of your time entries",
    request,
  });
