/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "time_entries", ":time_entry_id"],
    query: [
      {
        key: "project_id",
        value: "",
        description: "The ID of the project to associate with the time entry.",
        disabled: true,
      },
      {
        key: "task_id",
        value: "",
        description: "The ID of the task to associate with the time entry.",
        disabled: true,
      },
      {
        key: "spent_date",
        value: "",
        description: "The ISO 8601 formatted date the time entry was spent.",
        disabled: true,
      },
      {
        key: "started_time",
        value: "",
        description:
          "The time the entry started. Defaults to the current time. Example: “8:00am”.",
        disabled: true,
      },
      {
        key: "ended_time",
        value: "",
        description: "The time the entry ended.",
        disabled: true,
      },
      {
        key: "hours",
        value: "",
        description: "The current amount of time tracked.",
        disabled: true,
      },
      {
        key: "notes",
        value: "",
        description: "Any notes to be associated with the time entry.",
        disabled: true,
      },
      {
        key: "external_reference[id]",
        value: "",
        description: "The ID of the service's equivalent of a task, card, etc.",
        disabled: true,
      },
      {
        key: "external_reference[group_id]",
        value: "",
        description:
          "The ID of the service's equivalent of a project, board, etc.",
        disabled: true,
      },
      {
        key: "external_reference[permalink]",
        value: "",
        description: "The URL of where the time is being tracked.",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "time_entry_id",
        value: "",
        description: "The ID of the time entry you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific time entry by setting the values of the parameters passed",
    request,
  });
