/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "contacts <command>";
export const description = `Information pertaining to client contacts.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("contacts").version(false);
export const handler = () => {};
