/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
export const command = "contacts <command>";
export const description = `Information pertaining to client contacts.`;
export const builder: CommandBuilder = (yargs) =>
  yargs.commandDir("contacts").version(false);
