/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
import { commands } from "./line-items/index";
export const command = "line-items <command>";
export const description = `[Link to documentation](https://help.getharvest.com/api-v2/invoices-api/invoices/invoices/#the-invoice-line-item-object)`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .command(commands)
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
