/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./create";
import * as c1 from "./delete";
import * as c2 from "./list";
export const commands = [c0, c1, c2];
