/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./create";
import * as c1 from "./update";
import * as c2 from "./delete";
export const commands = [c0, c1, c2];
