/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "estimates", ":estimate_id"],
    query: [
      {
        key: "line_items[0]id",
        value: "",
        description: "The ID of the line item you want to update.",
      },
      {
        key: "line_items[0]kind",
        value: "",
        description: "The name of an estimate item category. ",
        disabled: true,
      },
      {
        key: "line_items[0]description",
        value: "",
        description: "Text description of the line item.",
        disabled: true,
      },
      {
        key: "line_items[0]unit_price",
        value: "",
        description: "The individual price per unit.",
        disabled: true,
      },
      {
        key: "line_items[0]quantity",
        value: "",
        description: "The unit quantity of the item.",
        disabled: true,
      },
      {
        key: "line_items[0]taxed",
        value: "",
        description:
          "Whether the estimate's tax percentage applies to this line item. ",
        disabled: true,
      },
      {
        key: "line_items[0]taxed2",
        value: "",
        description:
          "Whether the estimate's tax2 percentage applies to this line item.\n",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "estimate_id",
        value: "",
        description:
          "The ID of the estimate that contains the line item you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe: "Update an exisitng line item on an estimate",
    request,
  });
