/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "expense_categories"],
    query: [
      {
        key: "name",
        value: "",
        description: "The name of the expense category.",
      },
      {
        key: "unit_name",
        value: "",
        description: "The unit name of the expense category.",
        disabled: true,
      },
      {
        key: "unit_price",
        value: "",
        description: "The unit price of the expense category.\n",
        disabled: true,
      },
      {
        key: "is_active",
        value: "",
        description: "Whether the expense category is active or archived.\n",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "create",
    describe: "Retrieves the company for the currently authenticated user",
    request,
  });
