/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "expense_categories", ":expense_category_id"],
    query: [
      {
        key: "name",
        value: "",
        description: "The name of the expense category.",
        disabled: true,
      },
      {
        key: "unit_name",
        value: "",
        description: "The unit name of the expense category.",
        disabled: true,
      },
      {
        key: "unit_price",
        value: "",
        description: "The unit price of the expense category.\n",
        disabled: true,
      },
      {
        key: "is_active",
        value: "",
        description: "Whether the expense category is active or archived.\n",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "expense_category_id",
        value: "",
        description: "The ID of the expense category you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific expense category by setting the values of the parameters passed",
    request,
  });
