/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./create";
import * as c1 from "./delete";
import * as c2 from "./get";
import * as c3 from "./list";
import * as c4 from "./update";
export const commands = [c0, c1, c2, c3, c4];
