/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./alias";
import * as c1 from "./log-time";
import * as c2 from "./login";
import * as c3 from "./open";
import * as c4 from "./start-timer";
import * as c5 from "./status";
import * as c6 from "./stop-timer";
import * as c7 from "./timer-note";
export const commands = [c0, c1, c2, c3, c4, c5, c6, c7];
