/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./get";
import * as c1 from "./create";
import * as c2 from "./list";
import * as c3 from "./update";
import * as c4 from "./delete";
export const commands = [c0, c1, c2, c3, c4];
