/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "estimate_item_categories", ":estimate_item_category_id"],
    query: [
      {
        key: "name",
        value: "",
        description: "The name of the estimate item category.",
      },
    ],
    variable: [
      {
        key: "estimate_item_category_id",
        value: "",
        description: "The ID of the estimate item category you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific estimate item category by setting the values of the parameters passed",
    request,
  });
