/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "DELETE",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "invoices", ":invoice_id", "messages", ":message_id"],
    variable: [
      {
        key: "invoice_id",
        value: "",
        description:
          "The ID of the invoice that contains the message you are deleting.",
      },
      {
        key: "message_id",
        value: "",
        description: "The ID of the message you are deleting.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "delete",
    describe: "Delete an invoice message",
    request,
  });
