/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./create";
import * as c1 from "./delete";
import * as c2 from "./list-by-invoice";
import * as c3 from "./mark-draft-invoice-as-sent";
import * as c4 from "./mark-open-invoice-as-closed";
import * as c5 from "./mark-open-invoice-as-draft";
import * as c6 from "./re-open-closed-invoice";
export const commands = [c0, c1, c2, c3, c4, c5, c6];
