/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./billable-rates";
import * as c1 from "./cost-rates";
import * as c2 from "./create";
import * as c3 from "./delete";
import * as c4 from "./get";
import * as c5 from "./list";
import * as c6 from "./me";
import * as c7 from "./project-assignments";
import * as c8 from "./teammates";
import * as c9 from "./update";
export const commands = [
  c0 as CommandModule,
  c1 as CommandModule,
  c2 as CommandModule,
  c3 as CommandModule,
  c4 as CommandModule,
  c5 as CommandModule,
  c6 as CommandModule,
  c7 as CommandModule,
  c8 as CommandModule,
  c9 as CommandModule,
];
