/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "project-assignments <command>";
export const description = `Admin permissions required, except when retrieving the currently authenticated user’s project assignments.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("project-assignments").version(false);
export const handler = () => {};
