/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./expense-reports";
import * as c1 from "./project-budget-report";
import * as c2 from "./time-reports";
import * as c3 from "./uninvoiced-report";
export const commands = [c0, c1, c2, c3];
