/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./projects-time-report";
import * as c1 from "./team-time-report";
import * as c2 from "./clients-time-report";
import * as c3 from "./tasks-time-report";
export const commands = [c0, c1, c2, c3];
