/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./clients-time-report";
import * as c1 from "./projects-time-report";
import * as c2 from "./tasks-time-report";
import * as c3 from "./team-time-report";
export const commands = [
  c0 as CommandModule,
  c1 as CommandModule,
  c2 as CommandModule,
  c3 as CommandModule,
];
