/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import * as c0 from "./categories-report";
import * as c1 from "./clients-expense-report";
import * as c2 from "./projects-expense-report";
import * as c3 from "./team-expense-report";
export const commands = [c0, c1, c2, c3];
