/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "roles"],
    query: [
      { key: "name", value: "" },
      {
        key: "user_ids[]",
        value: "",
        description: "The IDs of the users assigned to this role.",
        disabled: true,
      },
      {
        key: "user_ids[]",
        value: "",
        description: "The IDs of the users assigned to this role.",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "create",
    describe: "Creates a new role object",
    request,
  });
