/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "GET",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "users", ":user_id", "billable_rates", ":billable_rate_id"],
    variable: [
      {
        key: "user_id",
        value: "",
        description:
          "The ID of the user whose billable rate you're retrieving.",
      },
      {
        key: "billable_rate_id",
        value: "",
        description: "The ID of the billable rate you're retrieving.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "get",
    describe: "Retrieves the billable rate with the given ID",
    request,
  });
