/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
export const command = "categories <command>";
export const description = `Information pertaining to retrieving, created, editing, and deleting expense categories.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .commandDir("categories")
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
