/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "expenses"],
    query: [
      {
        key: "project_id",
        value: "",
        description: "The ID of the project associated with this expense.",
      },
      {
        key: "expense_category_id",
        value: "",
        description:
          "The ID of the expense category this expense is being tracked against.",
      },
      {
        key: "spent_date",
        value: "",
        description: "Date the expense occurred.",
      },
      {
        key: "user_id",
        value: "",
        description:
          "The ID of the user associated with this expense. Defaults to the ID of the currently authenticated user.",
        disabled: true,
      },
      {
        key: "units",
        value: "",
        description:
          "The quantity of units to use in calculating the total_cost of the expense.",
        disabled: true,
      },
      {
        key: "total_cost",
        value: "",
        description: "The total amount of the expense.",
        disabled: true,
      },
      {
        key: "notes",
        value: "",
        description: "Textual notes used to describe the expense.\n",
        disabled: true,
      },
      {
        key: "billable",
        value: "",
        description:
          "Whether this expense is billable or not. Defaults to true.",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "create",
    describe: "Creates a new expense object",
    request,
  });
