/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../util/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "expenses", ":expense_id"],
    query: [
      {
        key: "project_id",
        value: "",
        description: "The ID of the project associated with this expense.",
        disabled: true,
      },
      {
        key: "expense_category_id",
        value: "",
        description:
          "The ID of the expense category this expense is being tracked against.",
        disabled: true,
      },
      {
        key: "spent_date",
        value: "",
        description: "Date the expense occurred.",
        disabled: true,
      },
      {
        key: "units",
        value: "",
        description:
          "The quantity of units to use in calculating the total_cost of the expense.",
        disabled: true,
      },
      {
        key: "total_cost",
        value: "",
        description: "The total amount of the expense.",
        disabled: true,
      },
      {
        key: "notes",
        value: "",
        description: "Textual notes used to describe the expense.\n",
        disabled: true,
      },
      {
        key: "billable",
        value: "",
        description: "Whether this expense is billable or not.",
        disabled: true,
      },
      {
        key: "delete_receipt",
        value: "",
        description:
          "Whether an attached expense receipt should be deleted. Pass true to delete the expense receipt.",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "expense_id",
        value: "",
        description: "The ID of the expense you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific expense by setting the values of the parameters passed",
    request,
  });
