/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "GET",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "projects", ":project_id", "task_assignments"],
    query: [
      {
        key: "is_active",
        value: "",
        description:
          "Pass true to only return active task assignments and false to return inactive task assignments.",
        disabled: true,
      },
      {
        key: "update_since",
        value: "",
        description:
          "Only return task assignments that have been updated since the given date and time.",
        disabled: true,
      },
      {
        key: "page",
        value: "",
        description:
          "The page number to use in pagination. Use `all` to retrieve all pages.",
        disabled: true,
      },
      {
        key: "per_page",
        value: "",
        description:
          "The number of records to return per page. Can range between 1 and 2000.",
        disabled: true,
      },
      { key: "", value: "" },
    ],
    variable: [
      {
        key: "project_id",
        value: "",
        description:
          "The ID of the project that contains the task assignments you're retrieving.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "list-by-project",
    describe:
      "Returns a list of your task assignments for the project identified by PROJECT_ID",
    request,
  });
