/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./get";
import * as c1 from "./list-by-user";
import * as c2 from "./create";
export const commands = [c0, c1, c2];
