/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./create";
import * as c1 from "./delete";
import * as c2 from "./list-by-estimate";
import * as c3 from "./mark-draft-estimate-as-sent";
import * as c4 from "./re-open-closed-estimate";
export const commands = [
  c0 as CommandModule,
  c1 as CommandModule,
  c2 as CommandModule,
  c3 as CommandModule,
  c4 as CommandModule,
];
