/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./list-by-estimate";
import * as c1 from "./mark-draft-estimate-as-sent";
import * as c2 from "./re-open-closed-estimate";
import * as c3 from "./create";
import * as c4 from "./delete";
export const commands = [c0, c1, c2, c3, c4];
