/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "estimates", ":estimates_id", "messages"],
    query: [
      {
        key: "event_type",
        value: "",
        description: "Pass “send” to mark the estimate as sent.",
      },
    ],
    variable: [
      {
        key: "estimates_id",
        value: "",
        description: "The ID of the estimate you're marking as sent.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "mark-draft-estimate-as-sent",
    describe:
      "Creates a new estimate message object and marks the estimate as sent",
    request,
  });
