/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "estimates", ":estimate_id", "messages"],
    query: [
      {
        key: "event_type",
        value: "",
        description: 'Pass "re-open" to re-open the estimate',
      },
    ],
    variable: [
      {
        key: "estimate_id",
        value: "",
        description: "The ID of the estimate you're re-opening.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "re-open-closed-estimate",
    describe:
      "Creates a new estimate message object and re-opens a closed estimate",
    request,
  });
