/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "invoice_item_categories", ":invoice_item_category_id"],
    query: [
      {
        key: "name",
        value: "",
        description: "The name of the invoice item category.",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "invoice_item_category_id",
        value: "",
        description: "The ID of the invoice item category you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific invoice item category by setting the values of the parameters passed",
    request,
  });
