/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./create";
import * as c1 from "./delete";
import * as c2 from "./get";
import * as c3 from "./list";
import * as c4 from "./task-assignments";
import * as c5 from "./update";
import * as c6 from "./user-assignments";
export const commands = [
  c0 as CommandModule,
  c1 as CommandModule,
  c2 as CommandModule,
  c3 as CommandModule,
  c4 as CommandModule,
  c5 as CommandModule,
  c6 as CommandModule,
];
