/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "GET",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "projects"],
    query: [
      {
        key: "is_active",
        value: "",
        description:
          "Pass true to only return active projects and false to return inactive projects.",
        disabled: true,
      },
      {
        key: "client_id",
        value: "",
        description:
          "Only return projects belonging to the client with the given ID.",
        disabled: true,
      },
      {
        key: "updated_since",
        value: "",
        description:
          "Only return projects that have been updated since the given date and time.",
        disabled: true,
      },
      {
        key: "page",
        value: "",
        description:
          "The page number to use in pagination. Use `all` to retrieve all pages.",
        disabled: true,
      },
      {
        key: "per_page",
        value: "",
        description:
          "The number of records to return per page. Can range between 1 and 100. (Default: 100)",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "list",
    describe: "Returns a list of your projects",
    request,
  });
