/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
import { commands } from "./task-assignments/index";
export const command = "task-assignments <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting task assignments. Admin or project manager permissions required.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .command(commands)
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
