/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "task-assignments <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting task assignments. Admin or project manager permissions required.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("task-assignments").version(false);
export const handler = () => {};
