/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "user-assignments <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting user assignments. Admin or project manager permissions required. Project managers can only see user assignments of projects they manage.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("user-assignments").version(false);
export const handler = () => {};
