/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./list-by-user";
import * as c1 from "./update";
export const commands = [c0 as CommandModule, c1 as CommandModule];
