/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "company <command>";
export const description = `Requests pertaining to companies.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("company").version(false);
export const handler = () => {};
