/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandModule } from "yargs";
import * as c0 from "./clients";
import * as c1 from "./company";
import * as c2 from "./estimates";
import * as c3 from "./expenses";
import * as c4 from "./invoices";
import * as c5 from "./projects";
import * as c6 from "./reports";
import * as c7 from "./roles";
import * as c8 from "./tasks";
import * as c9 from "./time-entries";
import * as c10 from "./users";
export const commands = [
  c0 as CommandModule,
  c1 as CommandModule,
  c2 as CommandModule,
  c3 as CommandModule,
  c4 as CommandModule,
  c5 as CommandModule,
  c6 as CommandModule,
  c7 as CommandModule,
  c8 as CommandModule,
  c9 as CommandModule,
  c10 as CommandModule,
];
