/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import * as c0 from "./projects";
import * as c1 from "./invoices";
import * as c2 from "./reports";
import * as c3 from "./clients";
import * as c4 from "./time-entries";
import * as c5 from "./roles";
import * as c6 from "./users";
import * as c7 from "./estimates";
import * as c8 from "./company";
import * as c9 from "./expenses";
import * as c10 from "./tasks";
export const commands = [c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10];
