/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
export const command = "invoices <command>";
export const description = `Admin or project manager permissions required.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .commandDir("invoices")
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
