/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "invoices <command>";
export const description = `Admin or project manager permissions required.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("invoices").version(false);
export const handler = () => {};
