/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
import { commands } from "./projects/index";
export const command = "projects <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting projects. Admin or project manager permissions required.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .command(commands)
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
