/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "projects <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting projects. Admin or project manager permissions required.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("projects").version(false);
export const handler = () => {};
