/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "roles <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting roles. Admin permissions and Team feature required.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("roles").version(false);
export const handler = () => {};
