/**
 * This file was generated by running `bun run generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
import { commands } from "./roles/index";
export const command = "roles <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting roles. Admin permissions and Team feature required.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .command(commands)
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
