/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "time-entries <command>";
export const description = `Information pertaining to retrieving, creating, editing, and deleting time entries.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("time-entries").version(false);
export const handler = () => {};
