/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { CommandBuilder } from "yargs";
export const command = "users <command>";
export const description = `Admin permissions required, except when retrieving the currently authenticated user.`;
export const builder: CommandBuilder = (yargs) =>
  yargs
    .commandDir("users")
    .demandCommand()
    .recommendCommands()
    .strictCommands()
    .version(false);
