/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import { Argv } from "yargs";
export const command = "users <command>";
export const description = `Admin permissions required, except when retrieving the currently authenticated user.`;
export const builder = (yargs: Argv) =>
  yargs.commandDir("users").version(false);
export const handler = () => {};
