/**
 * This file was generated by running `npm run generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: [
      "v2",
      "projects",
      ":project_id",
      "user_assignments",
      ":user_assignment_id",
    ],
    query: [
      {
        key: "is_active",
        value: "",
        description:
          "Pass true to only return active user assignments and false to return inactive user assignments.",
        disabled: true,
      },
      {
        key: "is_project_manager",
        value: "",
        description:
          "Determines if the user has project manager permissions for the project.",
        disabled: true,
      },
      {
        key: "use_default_rates",
        value: "",
        description:
          "Determines which billable rate(s) will be used on the project for this user when bill_by is People. When true, the project will use the user’s default billable rates. When false, the project will use the custom rate defined on this user assignment.",
        disabled: true,
      },
      {
        key: "hourly_rate",
        value: "",
        description:
          "Custom rate used when the project’s bill_by is People and use_default_rates is false.",
        disabled: true,
      },
      {
        key: "budget",
        value: "",
        description: "Budget used when the project’s budget_by is person.",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "project_id",
        value: "",
        description:
          "The ID of the project that contains the user assignment you're updating.",
      },
      {
        key: "user_assignment_id",
        value: "",
        description: "The ID of the user assignment you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific user assignment by setting the values of the parameters passed",
    request,
  });
