name: Deploy GitHub Pages

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Tests"]
  #   branches: [main]
  #   types:
  #     - completed

defaults:
  run:
    shell: bash
    working-directory: website

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
