name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: bun run format
      - run: bun run lint
      - run: bun run test
