/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../util/postman-request-command";

export const request: Request = {
  method: "POST",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "tasks"],
    query: [
      { key: "name", value: "", description: "The name of the task." },
      {
        key: "billable_by_default",
        value: "",
        description:
          "Used in determining whether default tasks should be marked billable when creating a new project. Defaults to true",
        disabled: true,
      },
      {
        key: "default_hourly_rate",
        value: "",
        description:
          "The default hourly rate to use for this task when it is added to a project. Defaults to 0.",
        disabled: true,
      },
      {
        key: "is_default",
        value: "",
        description:
          "Whether this task should be automatically added to future projects. Defaults to false.",
        disabled: true,
      },
      {
        key: "is_active",
        value: "",
        description:
          "Whether this task is active or archived. Defaults to true.",
        disabled: true,
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "create",
    describe: "Creates a new task object",
    request,
  });
