/**
 * This file was generated by running `yarn generate` and should NOT be modified.
 */
import postmanRequestCommand, {
  Request,
} from "../../utils/postman-request-command";

export const request: Request = {
  method: "PATCH",
  url: {
    protocol: "https",
    host: ["api", "harvestapp", "com"],
    path: ["v2", "tasks", ":task_id"],
    query: [
      {
        key: "name",
        value: "",
        description: " The name of the task.",
        disabled: true,
      },
      {
        key: "billable_by_default",
        value: "",
        description:
          "Used in determining whether default tasks should be marked billable when creating a new project.",
        disabled: true,
      },
      {
        key: "default_hourly_rate",
        value: "",
        description:
          "The default hourly rate to use for this task when it is added to a project.",
        disabled: true,
      },
      {
        key: "is_default",
        value: "",
        description:
          "Whether this task should be automatically added to future projects.",
        disabled: true,
      },
      {
        key: "is_active",
        value: "",
        description: "Whether this task is active or archived.",
        disabled: true,
      },
    ],
    variable: [
      {
        key: "task_id",
        value: "",
        description: "The ID of the task you're updating.",
      },
    ],
  },
};
export const { command, aliases, describe, builder, handler } =
  postmanRequestCommand({
    command: "update",
    describe:
      "Updates the specific task by setting the values of the parameters passed",
    request,
  });
